# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpartanDrive2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpartanDrive2
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Storage', '~> 0.6'
  target 'SpartanDrive2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpartanDrive2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
